---
- name: Restore Coolify Service
  hosts: controller
  become: true
  tasks:
    - name: Setup API Token
      ansible.builtin.include_role:
        name: coolify
        tasks_from: api_setup.yml

    - name: Ensure Service is deleted (optional)
      ansible.builtin.include_role:
        name: coolify-service
      vars:
        coolify_service_state: delete
      ignore_errors: true

    - name: Restore Service (Create)
      ansible.builtin.include_role:
        name: coolify-service
      vars:
        coolify_service_state: create
