---
coolify_api_base_url: "http://{{ 'host.docker.internal' if (inventory_hostname in (groups['controller'] | default([])) or inventory_hostname == 'noc.host.uk.com') else (hostvars[groups['controller'] | first]['ansible_host'] if groups['controller'] | default([]) | length > 0 else ansible_host) }}:8000/api/v1"
coolify_service_instant_deploy: true
coolify_service_envs: []
