---
- name: Delete Database
  ansible.builtin.uri:
    url: "{{ coolify_api_base_url }}/databases/{{ coolify_database_uuid }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ coolify_api_token }}"
    status_code: [200, 204]
  when: coolify_database_uuid is defined and coolify_database_uuid != ""
