---
- name: Delete Application
  ansible.builtin.uri:
    url: "{{ coolify_api_base_url }}/applications/{{ coolify_application_uuid }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ coolify_api_token }}"
    status_code: [200, 204]
  when: coolify_application_uuid is defined and coolify_application_uuid != ""
