---
- name: Create Coolify Service
  hosts: controller
  become: true
  tasks:
    - name: Setup API Token
      ansible.builtin.include_tasks: roles/coolify/tasks/api_setup.yml

    - name: Create Service
      ansible.builtin.include_role:
        name: coolify-service
      vars:
        coolify_service_state: create
