---
- name: Restore Coolify Application
  hosts: controller
  become: true
  tasks:
    - name: Setup API Token
      ansible.builtin.include_tasks: roles/coolify/tasks/api_setup.yml

    - name: Ensure Application is deleted (optional)
      ansible.builtin.include_role:
        name: coolify-application
      vars:
        coolify_application_state: delete
      ignore_errors: true

    - name: Restore Application (Create)
      ansible.builtin.include_role:
        name: coolify-application
      vars:
        coolify_application_state: create
