---
- name: Uninstall Coolify from controller host
  hosts: controller
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Run Coolify uninstallation tasks
      ansible.builtin.include_tasks:
        file: roles/coolify/tasks/uninstall.yml
      when: ansible_os_family == 'Debian'
