---
collections:
  - name: community.general
    version: ">=9.5.0"
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.docker
    version: ">=3.12.1"
  - name: community.crypto
    version: ">=2.20.0"
  - name: ansible.utils
    version: ">=5.1.0"
  - name: samdoran.macos
