---
parallels_vm_name: "vm-worker"
parallels_vm_template: "/Volumes/Data/VM/vm-template.pvm"
parallels_vm_cpu: 2
parallels_vm_memory: 2048
parallels_vm_user: root
parallels_vm_ssh_private_key_file: ~/.ssh/vm-worker
