### Site metadata ###

site_name: Bare Metal Coolify Infrastructure
site_description: Documentation for Bare Metal Coolify setup with Ansible

repo_url: https://host.uk.com
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  custom_dir: custom_theme/
  theme:
  features:
    - navigation.instant
    - navigation.sections
    - navigation.footer
    - toc.flow
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - Terminal Output:
    - Ansible: output/ansible.md
extra:
    generator: false

copyright: Copyright &copy; 2024 Ujstor
