---
- name: Restore Coolify Database
  hosts: controller
  become: true
  tasks:
    - name: Setup API Token
      ansible.builtin.include_role:
        name: coolify
        tasks_from: api_setup.yml

    - name: Ensure Database is deleted (optional)
      ansible.builtin.include_role:
        name: coolify-database
      vars:
        coolify_database_state: delete
      ignore_errors: true

    - name: Restore Database (Create)
      ansible.builtin.include_role:
        name: coolify-database
      vars:
        coolify_database_state: create
