---
- name: Delete Service
  ansible.builtin.uri:
    url: "{{ coolify_api_base_url }}/services/{{ coolify_service_uuid }}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ coolify_api_token }}"
    status_code: [200, 204]
  when: coolify_service_uuid is defined and coolify_service_uuid != ""
